# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - python setup.py build install
# command to run tests
script:
  - pytest
